import { Meteor } from 'meteor/meteor';
import { Mongo } from 'meteor/mongo';
import { DependencyList } from 'react';
export declare const useSubscription: (name?: string, ...args: any[]) => Meteor.SubscriptionHandle;
export declare const useCursor: <T = any>(factory: () => Mongo.Cursor<T>, deps?: DependencyList) => T[];
declare function useFind<T = any>(collection: Mongo.Collection<T>, query: any, deps: DependencyList): T[];
declare function useFind<T = any>(collection: Mongo.Collection<T>, query: any, options: any, deps: DependencyList): T[];
declare function useFindOne<T = any>(collection: Mongo.Collection<T>, query: any, deps: DependencyList): T;
declare function useFindOne<T = any>(collection: Mongo.Collection<T>, query: any, options: any, deps: DependencyList): T;
declare function useCount<T = any>(collection: Mongo.Collection<T>, query: any, deps: DependencyList): number;
declare function useCount<T = any>(collection: Mongo.Collection<T>, query: any, options: any, deps: DependencyList): number;
export { useFind, useFindOne, useCount };
