name: Meteor CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    name: Meteor react-packages tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Meteor
        uses: actions/cache@v4
        with:
          path: ~/.meteor
          key: meteor-cache

      - name: Setup Meteor
        uses: meteorengineer/setup-meteor@v2
        with:
          meteor-release: '3.1.2'

      - name: Prepare mtest
        run: |
          meteor npm i -g @zodern/mtest

      - name: Install and test in react-meteor-data
        working-directory: tests/react-meteor-data-harness
        run: |
          meteor npm install
          meteor npm run test:ci

      - name: Install and test in react-meteor-accounts-harness
        working-directory: tests/react-meteor-accounts-harness
        run: |
          meteor npm install
          meteor npm run test:ci
